apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: prod-local  # 초기값, tag push 시 CI가 바꿔줌

patches:
  - path: patch-deployment.yaml
