apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-prod
nameSuffix: -prod

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: 2dd432dbc4b8e0a7a82c05c4a923a9bbf12e2cbf

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml