spring:
  application:
    name: auth
  datasource:
    url: ${jifelog.database.url}
    username: ${jifelog.database.username}
    password: ${jifelog.database.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000
      idle-timeout: 60000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${jifelog.redis.host}
      port: 6379
      password: ${jifelog.redis.password}
      database: 0
      timeout: 2s
      lettuce:
        pool:
          max-active: 16
          max-idle: 16
          min-idle: 0
          max-wait: 1s
jifelog:
  mail:
    template-id:
      verification: bd10693a-62ef-4456-a172-a632f2cbdad5