apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev
nameSuffix: -dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: 09f02e5d85c50f4dccf0a6c6e26fd00741a5f848

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml