apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: c18e40da1a702a7ffde04f176a32b1307e33ea3a

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
