apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev
nameSuffix: -dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: 26a1ece406cf42e335b7f5fa202476bac61ab52c

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml