apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: 5d7924b3e32d1693d1a307f4309f7a7193a21ae2

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
