apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: e9a89517345212b7b7a9ff0313b214cd21a576f9

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
