apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev
nameSuffix: -dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: dev-a4aaae002d322b7b8921de40b6cd2998d7e63c29

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml