apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev
nameSuffix: -dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: 98b1aa88f7c969bdea57669bbbc44fbbb5f7cbc9

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml