apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: c80b7bcddb4d85d3f55ff2994391b9c19d0ed0ff

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
