apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: bba3cb837b6bd908ec6cc5ab623cc5aa02bd0e14

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
