name: CI (develop) - Build, Push Image, Update Kustomize

on:
  push:
    branches: ["develop"]
permissions:
  contents: write

concurrency:
  group: develop-cicd
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: gradle

      - name: Build jar
        run: |
          echo ${{secrets.SECRET_DATASOURCE}} | base64 --decode > ./src/main/resources/application-db.yaml
          
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
          ls -al build/libs

      # push 이벤트에서만 실행 (PR에서는 skip)
      - name: Set image metadata
        run: |
          echo "IMAGE_TAG=dev-${GITHUB_SHA}" >> $GITHUB_ENV
          echo "IMAGE_REPO=jhjun07/jifelog-auth-api" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${IMAGE_REPO}:${IMAGE_TAG} \
            -t ${IMAGE_REPO}:dev-latest \
            .

      # 7) Docker Hub로 푸시
      - name: Push Docker image
        run: |
          docker push ${IMAGE_REPO}:${IMAGE_TAG}
          docker push ${IMAGE_REPO}:dev-latest

      - name: Update Kustomize image tag (develop overlay) and push commit
        run: |
          FILE="k8s/overlays/develop/kustomization.yaml"
          sed -i "0,/newTag:/s/newTag:.*/newTag: ${IMAGE_TAG}/" "$FILE"

          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add "$FILE"
          git commit -m "chore: dev deploy ${IMAGE_TAG}" || echo "No changes to commit"
          git push
