name: CI (prod) - Build, Push Image, Update Kustomize

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions:
  contents: write

concurrency:
  group: prod-cicd
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: gradle

      - name: Build jar
        run: |
          echo ${{secrets.SECRET_DATASOURCE}} | base64 --decode > ./src/main/resources/application-db.yaml
          
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
          ls -al build/libs

      - name: Set image metadata
        run: |
          echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "IMAGE_REPO=jhjun07/jifelog-auth-api" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${IMAGE_REPO}:${IMAGE_TAG} \
            -t ${IMAGE_REPO}:prod-latest \
            .

      - name: Push Docker image
        run: |
          docker push ${IMAGE_REPO}:${IMAGE_TAG}
          docker push ${IMAGE_REPO}:prod-latest

      - name: Update Kustomize image tag (prod overlay) and push commit
        run: |
          FILE="k8s/overlays/prod/kustomization.yaml"
          sed -i "0,/newTag:/s/newTag:.*/newTag: ${IMAGE_TAG}/" "$FILE"

          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add "$FILE"
          git commit -m "chore: prod deploy ${IMAGE_TAG}" || echo "No changes to commit"
          git push
